### ISSUE TITLE
Question if you don’t mind on using Ganache

### ISSUE THREAD

**Issue by deckarep** [miguelmota/ethereum-development-with-go-book#1]
Hi @miguelmota,

Fantastic work on this book it’s written very well and so streamlined for getting up to speed.

Question for you though: do you think you can show an example of getting the Go client talking to Ganache which seems to be the de facto development version of the Blockchain? 

I mean, is it as simple as changing the DNS name to point to the local instance of Ganache?

I’d like to get that working but I haven’t investigated what it would all take but thought it would be useful in this book.

What do you think? And great work.

-Deckarep (Ralph)

**Comment by miguelmota** [comment]
@deckarep Thanks! glad it's useful 🙂

Talking to ganche is just as simple as talking to an infura endpoint. Here's are full instructions to help you get started (will include this in the book as well):

Install ganache

```bash
npm install -g ganache-cli
```

Run ganache cli

```
ganache-cli -m "much repair shock carbon improve miss forget sock include bullet interest solution"
```

Connect to ganache rpc host on `http://localhost:8545`

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, err := ethclient.Dial("http://localhost:8545")
	if err != nil {
		log.Fatal(err)
	}

	account := common.HexToAddress("0xe280029a7867ba5c9154434886c241775ea87e53")
	balance, err := client.BalanceAt(context.Background(), account, nil)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(balance) // 100000000000000000000
}
```

Let me you're having issues

**Comment by deckarep** [comment]
Bingo, this is what I was looking for.
I still think it would be worth adding to the book as an aside...but thanks for the detailed explanation.
Looks easy enough!

**Comment by miguelmota** [comment]
Awesome 👍 added to the setting up the client section

https://goethereumbook.org/client-setup/#using-ganache
