### ISSUE TITLE
Working on a Chinese Translation

### ISSUE THREAD

**Issue by qbig** [miguelmota/ethereum-development-with-go-book#10]
Will just park this here before it's done :)

**Comment by qbig** [comment]
https://github.com/miguelmota/ethereum-development-with-go-book/pull/11

**Comment by qbig** [comment]
Let me know how should I work on this? Incremental or PR after completion (that would be a giant PR tho)?

**Comment by qbig** [comment]
@gzuhlwang shall we split chapters?

**Comment by gzuhlwang** [comment]
thanks for invitation, I'd love to. Maybe I am familiar with the content before section 1.5.5(1.5.5 included). I wait for your feedback before I starting translating.

**Comment by qbig** [comment]
@gzuhlwang I will start from the final chapter and move backwards..

**Comment by miguelmota** [comment]
@qbig @gzuhlwang this is great 😃the community will really appreciate a Chinese translated version. I'll create a `lang-zh` branch and give you guys write access to it

**Comment by qbig** [comment]
@miguelmota That's awesome ! Thank you for creating such a great book in the first place. I read it and have already learned a lot.

**Comment by gzuhlwang** [comment]
@qbig I really appreciate your kindness. many thx.

**Comment by gzuhlwang** [comment]
@miguelmota  thanks you  who made this fantastic book a reality. I benefit from it a lot.

**Comment by miguelmota** [comment]
@gzuhlwang glad you found it useful

**Comment by gzuhlwang** [comment]
@miguelmota  hi, I commit local translation to remote branch `lang-zh`, but it reminds me permission denied. please give me write access to repo. thx.

**Comment by miguelmota** [comment]
@qbig make sure to accept the invite to gain write access to repo https://github.com/miguelmota/ethereum-development-with-go-book/invitations

**Comment by miguelmota** [comment]
@qbig @gzuhlwang great works guys! https://goethereumbook.org/zh/
