### ISSUE TITLE
Just a question on token event reading.

### ISSUE THREAD

**Issue by yueawang** [miguelmota/ethereum-development-with-go-book#18]
Hi, @miguelmota 

I am reading this github as I need to do something similar on ethereum, and I have to say this is a wonderful project and helps me a lot. 👍 
Here I have a question while reading "Reading ERC-20 Token Event Logs" section. There we have code as below:

> 			err := contractAbi.Unpack(&transferEvent, "Transfer", vLog.Data)
> 			if err != nil {
> 				log.Fatal(err)
> 			}
> 			
> 			transferEvent.From = common.HexToAddress(vLog.Topics[1].Hex()) // ?
> 			transferEvent.To = common.HexToAddress(vLog.Topics[2].Hex())     // ?
> 			
> 			fmt.Printf("From: %s\n", transferEvent.From.Hex())
> 			fmt.Printf("To: %s\n", transferEvent.To.Hex())
> 			fmt.Printf("Tokens: %s\n", transferEvent.Tokens.String()

My question is as this line
`err := contractAbi.Unpack(&transferEvent, "Transfer", vLog.Data)`
already parsed/unpacked the data (from/to fields from message), why we still need to get Hex data from vLog.Topics as below code shows ? 
> 			transferEvent.From = common.HexToAddress(vLog.Topics[1].Hex())
> 			transferEvent.To = common.HexToAddress(vLog.Topics[2].Hex())
Based on my understanding, Topics stores the message type Hash, we may not get the correct from/to by convert Topics[*].Hex to address, correct me if I am wrong. :)
Thanks!

**Comment by miguelmota** [comment]
@yueawang Thanks! and sorry it's not clear; the topics are `indexed` events. 

There can only be a maximum of 4 topics, the first topic is the event log signature hash.
The other 3 are optional and specified by the contract creator by using the `indexed` keyword.

`Unpack` unpacks the log data. The log data contains event arguments that are not indexed.
The [log event signature](https://theethereum.wiki/w/index.php/ERC20_Token_Standard) is: `event Transfer(address indexed from, address indexed to, uint tokens);` and as you can see `from` and `to` are `indexed` while `tokens` is not. 
So `from` and `to` are topics[1] and topics[2] respectively 

Hope this makes sense

**Comment by yueawang** [comment]
Thanks @miguelmota , that's crystal clear! 👍
