### ISSUE TITLE
Expired SSL Certificate

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [miguelmota/ethereum-development-with-go-book#32]
Hi..  just letting you know that the SSL cert for goethereumbook.org expired 2 days ago.

Thanks for producing such great content :)

**Comment by miguelmota** [comment]
@iamdefinitelyahuman thanks for the heads up! the cert is now updated, and thanks!

**Comment by iamdefinitelyahuman** [comment]
@miguelmota seems it's expired again.

**Comment by miguelmota** [comment]
@iamdefinitelyahuman thanks again. Need to setup a cron job to renew
