### ISSUE TITLE
Is there a bitcoin golang development book?

### ISSUE THREAD

**Issue by puzanov** [miguelmota/ethereum-development-with-go-book#4]
Just wonder if there any bitcoin go-lang development book?

**Comment by miguelmota** [comment]
@puzanov not that I know of. I'm pretty familiar with [btcd](https://github.com/btcsuite/btcd) though. Is there something in particular you'd like to learn? might write a tutorial like this book if you can tell me what things you'd like to learn 🙂

**Comment by puzanov** [comment]
thanks =)
