### ISSUE TITLE
cannot access https://etherconverter.online?

### ISSUE THREAD

**Issue by tsuu32** [miguelmota/ethereum-development-with-go-book#50]
https://github.com/miguelmota/ethereum-development-with-go-book/blob/c0c7adeb5febffcb092733e19ec5924aee7aeb43/en/transfer-eth/README.md#L43

I found a typo.
`[https://etherconverter.online](https://etherconverter.online])` should be
`[https://etherconverter.online](https://etherconverter.online)`.
But I cannot access `https://etherconverter.online` (dead link?).
How about changing to alternative one?

**Comment by miguelmota** [comment]
Thanks for reporting the typo and broken link. I've updated it to use https://etherconverter.netlify.com which is based on the [`ether-converter`](https://github.com/miguelmota/ether-converter/) npm package.
