### ISSUE TITLE
Simulated backend fails to run

### ISSUE THREAD

**Issue by visopsys** [miguelmota/ethereum-development-with-go-book#53]
I am trying to run the [client_simulated.go](https://github.com/miguelmota/ethereum-development-with-go-book/blob/master/code/client_simulated.go) and got an error: 
```
github.com/ethereum/go-ethereum/accounts/abi/bind/backends.(*SimulatedBackend).SendTransaction(0xc0002a0800, 0x48c5a40, 0xc00019a000, 0xc0002b2990, 0x0, 0x0)
	/Users/billy/gocode/pkg/mod/github.com/ethereum/go-ethereum@v1.9.18/accounts/abi/bind/backends/simulated.go:562 +0x5cd
main.main()
	/Users/billy/Desktop/study/online-course/ethereum-intro/goethereumbook/code/client_simulated.go:60 +0x56b
exit status 2
```

I am using geth 1.9.8. It seems like the chainID is not defined when we create the simulated backend.

I am not sure if we can fix this by modifying your code since there are only 2 functions that create a simulated backend `NewSimulatedBackendWithDatabase` and `NewSimulatedBackend` and they don't allow you to define chainID

**Comment by visopsys** [comment]
According to https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/backends/simulated_test.go#L64, we should use `HomesteadSigner` for testing with simulated backend.

**Comment by miguelmota** [comment]
@visopsys thanks for the bug report! I'll update the code samples.
