### ISSUE TITLE
send transactions tokens many-to-one 

### ISSUE THREAD

**Issue by emmeair** [miguelmota/ethereum-development-with-go-book#54]
How can a transaction instruction send tokens one-to-many or collect tokens many-to-one? Is there a specific example of golang implementation?

**Comment by miguelmota** [comment]
Sending one-to-many tokens in a single transaction requires a custom contract to facilitate the transfers. There's push or pull method ways of doing it. 

A custom proxy contract can be used to receive multiple tokens and this contract be set up to forward the tokens or allow an authorized key to withdraw the tokens.

I wish I had more time to do an example but there should be good examples that exists already out there, for [example](https://github.com/rstormsf/multisender/blob/b8cb76369bbe82aa841838b35e724c853fda54f0/contracts/contracts/multisender/UpgradebleStormSender.sol#L102).
