### ISSUE TITLE
Unpack parameters has changed

### ISSUE THREAD

**Issue by ncitron** [miguelmota/ethereum-development-with-go-book#55]
In the ebook, `ABI.Unpack` takes three arguments: `interface{}`, `string` and  `[]byte`. This seems to have changed in the recent versions of geth, which now has `Unpack` not take an interface, and instead returns a `[]interface{}` representing the event's data.

**Comment by aquavirgo** [comment]
Hi, 
please consider use UnpackIntoInterface(&transferEvent, "Transfer", vLog.Data)

best regards
