### ISSUE TITLE
abigen for complex contract example

### ISSUE THREAD

**Issue by huahuayu** [miguelmota/ethereum-development-with-go-book#56]
Hi, for all the example within the book, the contract is simple. What if the contract is a complex one(with many libraries and helper contract in it)?

Let's say, uniswap StakingRewards contract https://etherscan.io/address/0xCA35e32e7926b96A9988f61d510E038108d8068e#code

Can you demonstrate how to interact with it? Many `abi` and `bin` file will generate, but specifically, I want interactive with the contract`StakingRewards`.

Also, I try to interact with TetherToken https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code 

```bash
mkdir usdt
cd usdt
# touch TetherToken.sol and put code in it
solc --abi TetherToken.sol --out abi
solc --bin TetherToken.sol --out bin
abigen --bin=bin/TetherToken.bin --abi=abi/TetherToken.abi --pkg=usdt --out=usdt.go
```

then I get an error 

```text
Fatal: Failed to generate ABI binding: duplicated identifier "totalSupply"(normalized "TotalSupply"), use --alias for renaming
```

**Comment by huahuayu** [comment]
for the uniswap [StakingRewards contract](https://etherscan.io/address/0xCA35e32e7926b96A9988f61d510E038108d8068e#code), I have invoke it successfuly

But for tether token, abigen error: `use --alias for renaming` I don't konw how to solve it

**Comment by miguelmota** [comment]
Looks like the generated ABI has a `totalSupply`  method as well as a `_totalSupply` method so the problem is the generator will pascal case the names and remove special characters so they both become normalized to `TotalSupply` which creates an ambiguity conflict.

```json
[
  {
    "constant": true,
    "inputs": [],
    "name": "totalSupply",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "payable": false,
    "type": "function"
  },
  ...
  {
    "constant": true,
    "inputs": [],
    "name": "_totalSupply",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "payable": false,
    "type": "function"
  },
]
```

The solution is to use the `--alias` flag to change the name of one the ABI method names to something else so there's no conflict:

```bash
abigen --bin=bin/TetherToken.bin --abi=build/TetherToken.abi --pkg=usdt --out=usdt.go --alias _totalSupply=TotalSupply1
```

**Comment by huahuayu** [comment]
@miguelmota got it, thanks for the explain！
