### ISSUE TITLE
deploy contract and call a function in one go

### ISSUE THREAD

**Issue by huahuayu** [miguelmota/ethereum-development-with-go-book#59]
hi Miguel,

Usually, the process is to deploy contact first and then call the function.

But now the cost for deploy a contract is high. 

I wonder if I can deploy a contract and call a function within one transaction?

You may think why I want to do this because it's a special temporary contract, I just need to call the function once in mainnet , and what's more, I don't really need to submit it to chain, I just want to estimate gas for that function.

**Comment by huahuayu** [comment]
I get it, I can put that function call in the constructor, so it will be executed in deployment.

**Comment by miguelmota** [comment]
Yes that's the way to do it!
