### ISSUE TITLE
code out dated

### ISSUE THREAD

**Issue by huahuayu** [miguelmota/ethereum-development-with-go-book#61]
hi Miguel,

The below method does not exist anymore for `types.Transaction`

```go
	ts := types.Transactions{signedTx}
	rawTxBytes := ts.GetRlp(0)
```

so, this [file](https://github.com/miguelmota/ethereum-development-with-go-book/blob/master/en/transaction-raw-create/README.md) should update 

I test with go ethereum v1.10.2

I find there are another two functions should do this:

https://github.com/ethereum/go-ethereum/blob/beee6b77a0ca8c26881dc2bb17c58e996c90a0c6/core/types/transaction.go#L119

https://github.com/ethereum/go-ethereum/blob/beee6b77a0ca8c26881dc2bb17c58e996c90a0c6/core/types/transaction.go#L86

but I don't know what to put in the method param (w io.Writer)

**Comment by miguelmota** [comment]
@huahuayu Thanks for the bug report!

Here are some updated examples: 

`types.Transaction` to raw tx hex (using `MarshalBinary`):

```go
signedTx, err := types.SignTx(tx, types.NewEIP155Signer(chainID), privateKey)
if err != nil {
  log.Fatal(err)
}
rawTxBytes, err := signedTx.MarshalBinary()
if err != nil {
  log.Fatal(err)
}
rawTxHex := hex.EncodeToString(rawTxBytes)
fmt.Println(rawTxHex)
```

Raw tx hex to `type.Transaction` (using `UnmarshalBinary`):

```go
rawTxBytes, err = hex.DecodeString(rawTxHex)
t := types.Transaction{}
err = t.UnmarshalBinary(rawTxBytes)
if err != nil {
  log.Fatal(err)
}

spew.Dump(signedTx)
```

`types.Transaction` to raw tx hex (using `EncodeRLP`):

(this should generate the same tx hex data as the first example)

```go
var buf bytes.Buffer
err = signedTx.EncodeRLP(&buf)
if err != nil {
  log.Fatal(err)
}
rawTxHex := hex.EncodeToString(buf.Bytes())
fmt.Println(rawTxHex)
```

**Comment by huahuayu** [comment]
great!
