### ISSUE TITLE
website doesn't work & can't build the book from source

### ISSUE THREAD

**Issue by nazariyv** [miguelmota/ethereum-development-with-go-book#65]
website doesn't work both on mobile and desktop, something about an incorrect time of my computer / mobile

doesn't build from source due to node-gyp. Tried node v8, v10, v12 and v14

**Comment by miguelmota** [comment]
The ssl cert has been renewed so site should work now. 

I believe it'll only work with node v11 (see [.node-version](https://github.com/miguelmota/ethereum-development-with-go-book/blob/master/.node-version)) due to gitbook dependencies.

@nazariyv

**Comment by nazariyv** [comment]
haven't checked the building from the source, but the website is up, so I will close. Thank you, kindly!
