### ISSUE TITLE
Format to PullReuqest | Translate Spanish

### ISSUE THREAD

**Issue by FernandoFH** [miguelmota/ethereum-development-with-go-book#67]
Hi Miguel, 

I want to translate this material into Spanish

I wanted to know if you had any required PullReuqest format?

Regards.

**Comment by miguelmota** [comment]
Hey @FernandoFH!

A Spanish translation would be amazing for the community. To add a new translation, you can copy the the `en` directory, and replace the markdown content with the new translated content (you may use the chinese translation [PR](https://github.com/miguelmota/ethereum-development-with-go-book/pull/11) as a reference if needed) Let me know if you have any questions!
